spring:
  application:
    name: intellilearn-hub
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:192.168.221.100}:3306/exam_system_online?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123456}
  data:
    redis:
      host: ${REDIS_HOST:192.168.221.100}
      password: ${REDIS_PASSWORD:123456}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
server:
  port: 8080
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
intellilearn-hub:
  minio:
    access-key: ${MINIO_ACCESS_KEY:iMxRDoXHvtwE4TzKf3Do}
    secret-key: ${MINIO_SECRET_KEY:VsJMojzi9a0LI7lFJMHd5tuOgOl58vioKoWOo1te}
    bucket-name: ${MINIO_BUCKET_NAME:intellilearn-hub}
    endpoint: ${MINIO_ENDPOINT:http://192.168.221.100:9000}
  thread-pool:
    core-pool-size: 10
    maximum-pool-size: 30
    keep-alive-time: 300
    queue-capacity: 50
logging:
  level:
    root: info
    edu.jlu.intellilearnhub.server: debug
