spring:
  application:
    name: intellilearn-hub
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/exam_system_online?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123456}
server:
  port: 8080
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl